services:
  queryservice:
    build:
      context: ../
      dockerfile: build/queryservice/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - querydb

  commandservice:
    build:
      context: ../
      dockerfile: build/commandservice/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - commanddb

  commanddb:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: commanddb
    ports:
      - "3306:3306"
    volumes:
      - commanddb-data:/var/lib/mysql
    command: >
      --server-id=1          # サーバのID
      --log-bin=mysql-bin    # バイナリログを有効にし、ログファイルの名前を指定

  querydb:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: querydb
    ports:
      - "3307:3306"
    volumes:
      - querydb-data:/var/lib/mysql
    depends_on:
      - commanddb
    command: >
      --server-id=2                # スレーブサーバのID
      --log-bin                    # バイナリログを有効にする
      --relay-log=relay-bin        # リレーログファイルの名前
      --read-only=1                # 読み取り専用モード
      --replicate-do-db=commanddb  # レプリケートするデータベース: commanddb
      --master-host=commanddb      # マスターホストの名前
      --master-user=root           # マスターユーザ名
      --master-password=rootpassword # マスターユーザのパスワード
      --master-port=3306           # マスターポート

volumes:
  commanddb-data:
  querydb-data:
