services:
  queryservice:
    build:
      context: ../
      dockerfile: build/queryservice/go/Dockerfile
      target: dev
    working_dir: "/app"
    command: ["air", "-c", "/app/build/queryservice/go/.air.toml"]
    volumes:
      - ..:/app
    ports:
      - "8080:8080"
    environment:
      - ENV_FILE=env/.env.queryservice.dev
    depends_on:
      querydb:
        condition: service_healthy

  commandservice:
    build:
      context: ../
      dockerfile: build/commandservice/go/Dockerfile
      target: dev
    working_dir: "/app"
    command: ["air", "-c", "/app/build/commandservice/go/.air.toml"]
    volumes:
      - ..:/app
    ports:
      - "8081:8081"
    environment:
      - ENV_FILE=env/.env.commandservice.dev
    depends_on:
      commanddb:
        condition: service_healthy

  commanddb:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: commanddb
      MYSQL_USER: commanduser
      MYSQL_PASSWORD: commandpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - commanddb-data:/var/lib/mysql
      - ../internal/app/commandservice/infra/config/my.cnf:/etc/mysql/my.cnf
      - ../ddl:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  querydb:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: querydb
      MYSQL_USER: queryuser
      MYSQL_PASSWORD: querypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - querydb-data:/var/lib/mysql
      - ../internal/app/queryservice/infra/config/my.cnf:/etc/mysql/my.cnf
      - ../ddl:/docker-entrypoint-initdb.d/ddl # DDLスクリプトを格納するディレクトリ
      - ../internal/app/queryservice/infra/config/init.sh:/docker-entrypoint-initdb.d/init.sh # 初期化スクリプト
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      commanddb:
        condition: service_healthy

volumes:
  commanddb-data:
  querydb-data:
