services:
  queryservice:
    build:
      context: ../
      dockerfile: build/queryservice/go/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - querydb

  commandservice:
    build:
      context: ../
      dockerfile: build/commandservice/go/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - commanddb

  commanddb:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: commanddb
      MYSQL_USER: commanduser
      MYSQL_PASSWORD: commandpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - commanddb-data:/var/lib/mysql
      - ../internal/app/commandservice/infra/config/my.cnf:/etc/mysql/my.cnf

  querydb:
    build:
      context: ../
      dockerfile: build/queryservice/mysql/Dockerfile
    environment:
      MYSQL_DATABASE: querydb
      MYSQL_USER: queryuser
      MYSQL_PASSWORD: querypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - querydb-data:/var/lib/mysql
    depends_on:
      - commanddb

volumes:
  commanddb-data:
  querydb-data:
